plaintext
* NPN Transistor Circuit

VCC 1 0 DC 10V

R1 1 2  [RESISTANCE_VALUE]
R2 2 4  [RESISTANCE_VALUE]
RC 1 3  [RESISTANCE_VALUE]
RE 4 0  [RESISTANCE_VALUE]

Q1 3 2 4 NPN

.model NPN NPN (IS=[SATURATION_CURRENT] BF=[FORWARD_BETA] VAF=[EARLY_VOLTAGE])

* End of Netlist