spice
* SPICE Netlist for the schematic

M1 6 5 0 0 NMOS L=VALUE W=VALUE
M2 2 5 0 0 NMOS L=VALUE W=VALUE
M3 2 3 4 4 PMOS L=VALUE W=VALUE
M4 6 3 4 4 PMOS L=VALUE W=VALUE

IREF 6 0 DC VALUE

VDD 4 0 DC VALUE

*.model NMOS NMOS LEVEL=<LEVEL> <OTHER_PARAMETERS>
*.model PMOS PMOS LEVEL=<LEVEL> <OTHER_PARAMETERS>

*.end